### ISSUE TITLE
File browser branch compiling issues

### ISSUE THREAD

**Issue by TriforceOfPwnage** [Gericom/GBARunner2#9]
I cant seem to get the file browser branch to compile it keeps spitting out an error 
this is the cmd window output after i run make 

C:\Users\Thomas\Downloads\GBARunner2-file_explorer\GBARunner2-file_explorer>make
make -C arm7
make[1]: Entering directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm7'
make[2]: `/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm7/GBARunner2-file_explorer.elf' is up to date.
make[1]: Leaving directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm7'
make -C arm9
make[1]: Entering directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm9'
linking GBARunner2-file_explorer.elf
sd_access.o: In function `get_folder_contents(vector_&, unsigned long)':
c:/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm9/source/sd_access.cpp:258: undefined reference to `memset'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm9/GBARunner2-file_explorer.elf] Error 1
make[1]: *** [build] Error 2
make[1]: Leaving directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer/GBARunner2-file_explorer/arm9'
make: *** [arm9/GBARunner2-file_explorer.elf] Error 2

C:\Users\Thomas\Downloads\GBARunner2-file_explorer\GBARunner2-file_explorer>

**Comment by Gericom** [comment]
Could you try to run make clean before running make?

**Comment by Gericom** [comment]
Okay, I think I fixed it in 3860043dba78dc80bc9a5afede288342e4152566
Newer versions of gcc tend to generate more calls to std functions. And I can't find a way to turn that completely off.

**Comment by TriforceOfPwnage** [comment]
tried the new commit and nope, no dice, still isnt compiling

**Comment by Gericom** [comment]
Could you do a make clean again and post the error message here?

**Comment by TriforceOfPwnage** [comment]
Here's what shows up in the cmd window

C:\Users\Thomas\Downloads\GBARunner2-file_explorer (2)\GBARunner2-file_explorer>make
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `basename /c/Users/Thomas/Downloads/GBARunner2-file_explorer (2)/GBARunner2-file_explorer'
make -C arm7
make[1]: Entering directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer (2)/GBARunner2-file_explorer/arm7'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `make --no-print-directory -C build -f /c/Users/Thomas/Downloads/GBARunner2-file_explorer (2)/GBARunner2-file_explorer/arm7/Makefile'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/c/Users/Thomas/Downloads/GBARunner2-file_explorer (2)/GBARunner2-file_explorer/arm7'
make: *** [arm7/.elf] Error 2

**Comment by Gericom** [comment]
It must be the space in your path. Make hates those
